// prelude.c — prelude.rho embedded verbatim (generated form; the
// .rho file is the source of truth — regenerate with
// tools/embed_prelude.py).
const char *prelude_src(void) {
  return
    "// prelude.rho — the kernel, part 1 (grows to its full form in T1.8).\n"
    "// Loaded before every program; its public names are the prelude.\n"
    "// printf/eprintf/format/len/panic/assert are compiler-intrinsic call\n"
    "// targets: their signatures here anchor checking, the emitter\n"
    "// implements them (format desugar per spec §5, panic per spec §2).\n"
    "\n"
    "// The print protocol as a trait (§8): satisfaction is computed from\n"
    "// the method tables — every primitive's to_str below implements it,\n"
    "// and a user type joins by defining to_str (an impl block only adds\n"
    "// the eager check). Each primitive rides the emitter's native format\n"
    "// path, so the digits are one source with printf's own.\n"
    "pub trait Show {\n"
    "  fn to_str(self) -> string,\n"
    "}\n"
    "\n"
    "// None rides tag 0: zeroed allocations (make/new, §2) read as the\n"
    "// absent form — a fresh []?T slot is None, not Some(junk)\n"
    "pub enum Option[T] {\n"
    "  None,\n"
    "  Some(T),\n"
    "}\n"
    "\n"
    "pub enum Result[T, E] {\n"
    "  Ok(T),\n"
    "  Err(E),\n"
    "}\n"
    "\n"
    "fn i8.to_str(self: i8) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn i16.to_str(self: i16) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn i32.to_str(self: i32) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn i64.to_str(self: i64) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn u8.to_str(self: u8) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn u16.to_str(self: u16) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn u32.to_str(self: u32) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn u64.to_str(self: u64) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn usize.to_str(self: usize) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn f32.to_str(self: f32) -> string {\n"
    "  return __f32_text(self);\n"
    "}\n"
    "\n"
    "fn f64.to_str(self: f64) -> string {\n"
    "  return __f64_text(self);\n"
    "}\n"
    "\n"
    "fn bool.to_str(self: bool) -> string {\n"
    "  return format(\"{}\", self);\n"
    "}\n"
    "\n"
    "fn string.to_str(self: string) -> string {\n"
    "  return self;\n"
    "}\n"
    "\n"
    "pub fn printf(fmt: string) {}\n"
    "\n"
    "pub fn eprintf(fmt: string) {}\n"
    "\n"
    "pub fn format(fmt: string) -> string {\n"
    "  return fmt;\n"
    "}\n"
    "\n"
    "pub fn len(s: string) -> usize {\n"
    "  return 0 as usize;\n"
    "}\n"
    "\n"
    "pub fn make() -> usize { return 0 as usize; }\n"
    "\n"
    "pub fn panic(msg: string) {}\n"
    "\n"
    "pub fn assert(cond: bool, msg: string) {}\n"
    "\n"
    "pub fn assert_eq[T: Show](a: T, b: T) {\n"
    "  if !(a == b) {\n"
    "    panic(\"assert_eq failed: \" + a.to_str() + \" != \" + b.to_str());\n"
    "  }\n"
    "}\n"
    "\n"
    "pub fn exit(code: i32) {}\n"
    "\n"
    "// ------------------------------------------------------------ floats\n"
    "//\n"
    "// Exact decimal text for f32/f64 (the to_str family, kernel-private):\n"
    "// the value is m·2^e; a base-1e9 limb vector expands it exactly\n"
    "// (multiplying by 5^-e when e<0, so the value is N/10^sc in integers),\n"
    "// then rounds half-to-even to the round-trip digit count (17 f64,\n"
    "// 9 f32) and prints positionally or scientifically. Pure integer\n"
    "// arithmetic — the only bit access is the intrinsics window (§2).\n"
    "\n"
    "struct Dec {\n"
    "  limbs: []u32,\n"
    "  used: usize,\n"
    "}\n"
    "\n"
    "fn dec_new() -> *Dec {\n"
    "  return new Dec { limbs: make([]u32, 96), used: 1 };\n"
    "}\n"
    "\n"
    "fn dec_trim(mut d: *Dec) {\n"
    "  while d.used > 1 && d.limbs[d.used - 1] == 0 {\n"
    "    d.used = d.used - 1;\n"
    "  }\n"
    "  return;\n"
    "}\n"
    "\n"
    "fn dec_set(mut d: *Dec, v: u64) {\n"
    "  d.limbs[0] = (v % 1000000000) as u32;\n"
    "  d.limbs[1] = ((v / 1000000000) % 1000000000) as u32;\n"
    "  d.limbs[2] = (v / 1000000000000000000) as u32;\n"
    "  d.used = 3;\n"
    "  dec_trim(mut d);\n"
    "  return;\n"
    "}\n"
    "\n"
    "fn dec_mul_small(mut d: *Dec, m: u32) {\n"
    "  let mut carry: u64 = 0;\n"
    "  let mut i: usize = 0;\n"
    "  while i < d.used {\n"
    "    let cur: u64 = (d.limbs[i] as u64) * (m as u64) + carry;\n"
    "    d.limbs[i] = (cur % 1000000000) as u32;\n"
    "    carry = cur / 1000000000;\n"
    "    i = i + 1;\n"
    "  }\n"
    "  while carry > 0 {\n"
    "    d.limbs[d.used] = (carry % 1000000000) as u32;\n"
    "    carry = carry / 1000000000;\n"
    "    d.used = d.used + 1;\n"
    "  }\n"
    "  return;\n"
    "}\n"
    "\n"
    "fn dec_to_u64(d: *Dec) -> u64 {\n"
    "  let mut v: u64 = 0;\n"
    "  let mut i: usize = d.used;\n"
    "  while i > 0 {\n"
    "    i = i - 1;\n"
    "    v = v * 1000000000 + (d.limbs[i] as u64);\n"
    "  }\n"
    "  return v;\n"
    "}\n"
    "\n"
    "fn dec_bump(mut d: *Dec) {\n"
    "  let mut i: usize = 0;\n"
    "  loop {\n"
    "    if i >= d.used {\n"
    "      d.limbs[i] = 1;\n"
    "      d.used = d.used + 1;\n"
    "      return;\n"
    "    }\n"
    "    if d.limbs[i] + 1 < 1000000000 {\n"
    "      d.limbs[i] = d.limbs[i] + 1;\n"
    "      return;\n"
    "    }\n"
    "    d.limbs[i] = 0;\n"
    "    i = i + 1;\n"
    "  }\n"
    "}\n"
    "\n"
    "fn dec_cmp(a: *Dec, b: *Dec) -> i32 {\n"
    "  if a.used != b.used {\n"
    "    if a.used < b.used {\n"
    "      return -1;\n"
    "    }\n"
    "    return 1;\n"
    "  }\n"
    "  let mut i: usize = a.used;\n"
    "  while i > 0 {\n"
    "    i = i - 1;\n"
    "    if a.limbs[i] != b.limbs[i] {\n"
    "      if a.limbs[i] < b.limbs[i] {\n"
    "        return -1;\n"
    "      }\n"
    "      return 1;\n"
    "    }\n"
    "  }\n"
    "  return 0;\n"
    "}\n"
    "\n"
    "fn pow10_u64(r: usize) -> u64 {\n"
    "  let mut v: u64 = 1;\n"
    "  let mut i: usize = 0;\n"
    "  while i < r {\n"
    "    v = v * 10;\n"
    "    i = i + 1;\n"
    "  }\n"
    "  return v;\n"
    "}\n"
    "\n"
    "fn pow2_small(k: i32) -> u32 {\n"
    "  let mut v: u32 = 1;\n"
    "  let mut i: i32 = 0;\n"
    "  while i < k {\n"
    "    v = v * 2;\n"
    "    i = i + 1;\n"
    "  }\n"
    "  return v;\n"
    "}\n"
    "\n"
    "fn pow5_small(k: i32) -> u32 {\n"
    "  let mut v: u32 = 1;\n"
    "  let mut i: i32 = 0;\n"
    "  while i < k {\n"
    "    v = v * 5;\n"
    "    i = i + 1;\n"
    "  }\n"
    "  return v;\n"
    "}\n"
    "\n"
    "fn dec_top_digits(d: *Dec) -> i32 {\n"
    "  let mut x: u32 = d.limbs[d.used - 1];\n"
    "  let mut n: i32 = 1;\n"
    "  while x >= 10 {\n"
    "    x = x / 10;\n"
    "    n = n + 1;\n"
    "  }\n"
    "  return n;\n"
    "}\n"
    "\n"
    "// 5·10^(cut-1): half of the divisor 10^cut\n"
    "fn dec_half_of(cut: usize) -> *Dec {\n"
    "  let mut h: *Dec = dec_new();\n"
    "  let pos: usize = cut - 1;\n"
    "  let l: usize = pos / 9;\n"
    "  let r: usize = pos % 9;\n"
    "  h.limbs[l] = (5 * pow10_u64(r)) as u32;\n"
    "  h.used = l + 1;\n"
    "  return h;\n"
    "}\n"
    "\n"
    "// q = d div 10^cut (returned); d keeps d mod 10^cut\n"
    "fn dec_split(mut d: *Dec, cut: usize) -> *Dec {\n"
    "  let l: usize = cut / 9;\n"
    "  let r: usize = cut % 9;\n"
    "  let mut q: *Dec = dec_new();\n"
    "  if d.used <= l {\n"
    "    return q;\n"
    "  }\n"
    "  let qn: usize = d.used - l;\n"
    "  let p: u64 = pow10_u64(r);\n"
    "  let mut rem: u64 = 0;\n"
    "  let mut i: usize = qn;\n"
    "  while i > 0 {\n"
    "    i = i - 1;\n"
    "    let cur: u64 = rem * 1000000000 + (d.limbs[l + i] as u64);\n"
    "    q.limbs[i] = (cur / p) as u32;\n"
    "    rem = cur % p;\n"
    "  }\n"
    "  q.used = qn;\n"
    "  dec_trim(mut q);\n"
    "  if r > 0 {\n"
    "    d.limbs[l] = rem as u32;\n"
    "    d.used = l + 1;\n"
    "  } else {\n"
    "    d.used = l;\n"
    "  }\n"
    "  if d.used == 0 {\n"
    "    d.limbs[0] = 0;\n"
    "    d.used = 1;\n"
    "  }\n"
    "  dec_trim(mut d);\n"
    "  return q;\n"
    "}\n"
    "\n"
    "fn drop_zeros(s: string) -> string {\n"
    "  let mut k: usize = len(s);\n"
    "  while k > 0 && s[k - 1] == 48 {\n"
    "    k = k - 1;\n"
    "  }\n"
    "  return s[0..k];\n"
    "}\n"
    "\n"
    "fn signed(neg: bool, body: string) -> string {\n"
    "  if neg {\n"
    "    return \"-\" + body;\n"
    "  }\n"
    "  return body;\n"
    "}\n"
    "\n"
    "fn dec_text(x: f64, prec: i32) -> string {\n"
    "  let bits: u64 = intrinsics.f64_bits(x);\n"
    "  // NaN prints canonically unsigned (its sign bit is hardware-defined)\n"
    "  let neg: bool = (bits >> 63) == 1;\n"
    "  let mag: u64 = bits & 9223372036854775807;\n"
    "  let biased: u64 = (mag >> 52) & 2047;\n"
    "  if biased == 2047 {\n"
    "    if (mag & 4503599627370495) == 0 {\n"
    "      return signed(neg, \"inf\");\n"
    "    }\n"
    "    return \"nan\";\n"
    "  }\n"
    "  if (mag << 1) == 0 {\n"
    "    return signed(neg, \"0.0\");\n"
    "  }\n"
    "  let mut m: u64 = 0;\n"
    "  let mut e: i64 = 0;\n"
    "  if biased == 0 {\n"
    "    m = mag & 4503599627370495;\n"
    "    e = -1074;\n"
    "  } else {\n"
    "    m = (mag & 4503599627370495) | 4503599627370496;\n"
    "    e = (biased as i64) - 1075;\n"
    "  }\n"
    "  // exact digits: x == N / 10^sc\n"
    "  let mut d: *Dec = dec_new();\n"
    "  dec_set(mut d, m);\n"
    "  let mut sc: i64 = 0;\n"
    "  if e >= 0 {\n"
    "    let mut k: i64 = e;\n"
    "    while k >= 29 {\n"
    "      dec_mul_small(mut d, 536870912);\n"
    "      k = k - 29;\n"
    "    }\n"
    "    if k > 0 {\n"
    "      dec_mul_small(mut d, pow2_small(k as i32));\n"
    "    }\n"
    "  } else {\n"
    "    let mut k: i64 = -e;\n"
    "    while k >= 12 {\n"
    "      dec_mul_small(mut d, 244140625);\n"
    "      sc = sc + 12;\n"
    "      k = k - 12;\n"
    "    }\n"
    "    if k > 0 {\n"
    "      dec_mul_small(mut d, pow5_small(k as i32));\n"
    "      sc = sc + k;\n"
    "    }\n"
    "  }\n"
    "  // n: x == 0.<digits> × 10^n; keep prec significant digits\n"
    "  let topd: i32 = dec_top_digits(d);\n"
    "  let mut n: i64 = ((d.used as i64) - 1) * 9 + (topd as i64) - sc;\n"
    "  let cut: i64 = sc + n - (prec as i64);\n"
    "  let mut qv: u64 = 0;\n"
    "  if cut > 0 {\n"
    "    let mut q: *Dec = dec_split(mut d, cut as usize);\n"
    "    let c: i32 = dec_cmp(d, dec_half_of(cut as usize));\n"
    "    if c > 0 || (c == 0 && (q.limbs[0] & 1) == 1) {\n"
    "      dec_bump(mut q);\n"
    "    }\n"
    "    qv = dec_to_u64(q);\n"
    "  } else {\n"
    "    if cut == 0 {\n"
    "      qv = dec_to_u64(d);\n"
    "    } else {\n"
    "      let mut k: i64 = -cut;\n"
    "      while k >= 9 {\n"
    "        dec_mul_small(mut d, 1000000000);\n"
    "        k = k - 9;\n"
    "      }\n"
    "      if k > 0 {\n"
    "        dec_mul_small(mut d, pow10_u64(k as usize) as u32);\n"
    "      }\n"
    "      qv = dec_to_u64(d);\n"
    "    }\n"
    "  }\n"
    "  let mut ds: string = format(\"{}\", qv);\n"
    "  if qv >= pow10_u64(prec as usize) {\n"
    "    // carry: 99…9.7 rounded up grew a digit\n"
    "    qv = qv / 10;\n"
    "    n = n + 1;\n"
    "    ds = format(\"{}\", qv);\n"
    "  }\n"
    "  let e10: i64 = n - 1;\n"
    "  if e10 >= -4 && e10 < (prec as i64) {\n"
    "    if e10 >= 0 {\n"
    "      let ip: usize = (e10 as usize) + 1;\n"
    "      let frac: string = drop_zeros(ds[ip..prec as usize]);\n"
    "      if len(frac) == 0 {\n"
    "        return signed(neg, ds[0..ip]);\n"
    "      }\n"
    "      return signed(neg, ds[0..ip] + \".\" + frac);\n"
    "    }\n"
    "    let all: string = drop_zeros(ds);\n"
    "    if len(all) == 0 {\n"
    "      return signed(neg, \"0\");\n"
    "    }\n"
    "    let mut pre: string = \"0.\";\n"
    "    let mut j: i64 = (-e10) - 1;\n"
    "    while j > 0 {\n"
    "      pre = pre + \"0\";\n"
    "      j = j - 1;\n"
    "    }\n"
    "    return signed(neg, pre + all);\n"
    "  }\n"
    "  let mut out: string = ds[0..1];\n"
    "  let frac: string = drop_zeros(ds[1..prec as usize]);\n"
    "  if len(frac) > 0 {\n"
    "    out = out + \".\" + frac;\n"
    "  }\n"
    "  let mut ae: i64 = e10;\n"
    "  if ae < 0 {\n"
    "    ae = -ae;\n"
    "  }\n"
    "  let mut es: string = format(\"{}\", ae);\n"
    "  if ae < 10 {\n"
    "    es = \"0\" + es;\n"
    "  }\n"
    "  if e10 < 0 {\n"
    "    return signed(neg, out + \"e-\" + es);\n"
    "  }\n"
    "  return signed(neg, out + \"e+\" + es);\n"
    "}\n"
    "\n"
    "// integral floats keep a visible fraction (\"4\" reads as \"4.0\")\n"
    "fn with_frac(s: string) -> string {\n"
    "  if s == \"inf\" || s == \"nan\" || s == \"-inf\" {\n"
    "    return s;\n"
    "  }\n"
    "  let mut i: usize = 0;\n"
    "  while i < len(s) {\n"
    "    if s[i] == 46 || s[i] == 101 {\n"
    "      return s;\n"
    "    }\n"
    "    i = i + 1;\n"
    "  }\n"
    "  return s + \".0\";\n"
    "}\n"
    "\n"
    "fn __f64_text(x: f64) -> string {\n"
    "  return with_frac(dec_text(x, 17));\n"
    "}\n"
    "\n"
    "fn __f32_text(x: f32) -> string {\n"
    "  // f32 values are exact in f64; 9 significant digits round-trip f32\n"
    "  return with_frac(dec_text(x as f64, 9));\n"
    "}\n";
      ;
}
