// TypeScript declaration rendering for a compiled .rho module.
//
// Rich typing for primitives and strings; raw pointer-level typing for
// slices/pointers; excluded declarations (generics, struct/enum/fn-typed
// signatures) render as documented comments so intent is visible in the IDE.

import { abiOfRhoType, isPointerLike, isSlice, nonceFor, type RhoSignature } from './bridge.js';

export interface DtsOptions {
  /** Every top-level pub fn (sorted by name), supported or not. */
  signatures: RhoSignature[];
  /** Names actually re-exported by the companion module. */
  exportNames: string[];
}

function tsType(rhoType: string): string {
  const t = rhoType.trim();
  const abi = abiOfRhoType(t);
  if (t === 'bool') return 'boolean';
  if (abi.kind === 'i64') return 'bigint';
  if (abi.kind === 'i32' || abi.kind === 'f32' || abi.kind === 'f64') return 'number';
  if (abi.kind === 'str') return 'string';
  if (isPointerLike(t) || isSlice(t)) return 'number';
  return 'never'; // excluded declarations never reach here
}

/** Render the `.d.rho.ts` declaration file content. */
export function generateDts(options: DtsOptions): string {
  const { signatures, exportNames } = options;
  const exported = new Set(exportNames);
  const lines: string[] = [];
  lines.push(`// Generated by vite-plugin-rho — do not edit.`);
  lines.push(`// Types for the functions exported by this rho module.`);
  lines.push('');

  for (const sig of signatures) {
    if (sig.generic) {
      lines.push(`// ${sig.name}(...) — not exported: generic functions cannot be called uninstantiated.`);
      continue;
    }
    if (sig.unsupportedReason) {
      lines.push(`// ${sig.name}(...) — not exported: ${sig.unsupportedReason}.`);
      continue;
    }
    if (!exported.has(sig.name)) {
      lines.push(`// ${sig.name}(...) — not exported by the build configuration.`);
      continue;
    }

    const docLines: string[] = [];
    const params = sig.params.map((p) => {
      if (isPointerLike(p.type)) {
        docLines.push(` * @param ${p.name} — raw address inside rho linear memory (advanced)`);
      } else if (isSlice(p.type)) {
        docLines.push(` * @param ${p.type} ${p.name} — raw slice pointer into rho linear memory (advanced)`);
      }
      return `${p.name}: ${tsType(p.type)}`;
    });
    let ret: string;
    if (!sig.ret) {
      ret = 'void';
    } else {
      const kind = abiOfRhoType(sig.ret).kind;
      if (kind === 'agg' && !isPointerLike(sig.ret) && !isSlice(sig.ret)) {
        ret = 'number';
        docLines.push(' * Returns the raw address of the returned value (advanced).');
      } else {
        ret = tsType(sig.ret);
      }
    }
    if (docLines.length) {
      lines.push('/**');
      for (const d of docLines) lines.push(d);
      lines.push(' */');
    }
    lines.push(`export declare function ${sig.name}(${params.join(', ')}): ${ret};`);
    lines.push('');
  }
  return lines.join('\n');
}

/** The nonce argument list a companion call must pass, as JS literals. */
export function nonceArgsJs(k: number): string {
  return nonceFor(k)
    .map((vt) => (vt === 'i64' ? '0n' : '0'))
    .join(', ');
}
