#!/usr/bin/env python3
"""Embed boot/wat/kernel.wat into boot/kernel_wat.c (deterministic)."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "boot" / "wat" / "kernel.wat"
DST = ROOT / "boot" / "kernel_wat.c"


def main() -> int:
    src = SRC.read_bytes().decode("utf-8")
    # strip the smoke-test function: the emitter embeds the kernel
    # piecewise; the smoke entry exists for standalone validation only
    if ";; smoke:" in src:
        src = src[: src.index(";; smoke:")]
        src = src.rstrip() + "\n)\n" # restore the module close
    # strip the emitter-owned region (the emitter emits its own table)
    if ";; EMITTER-OWNS-BEGIN" in src:
        a = src.index(";; EMITTER-OWNS-BEGIN")
        b = src.index(";; EMITTER-OWNS-END") + len(";; EMITTER-OWNS-END")
        src = src[:a] + src[b:]
    lines = [ln for ln in src.split("\n") if ln.strip()]
    out = [
        "// kernel_wat.c — boot/wat/kernel.wat embedded (generated by",
        "// tools/embed_kernel.py; the .wat file is the source of truth).",
        'const char *kernel_wat_src(void) {',
        "  return",
    ]
    esc = []
    for ln in lines:
        # one WAT line per C string fragment
        esc.append('    "%s\\n"' % ln.replace("\\", "\\\\").replace('"', '\\"'))
    out.append("\n".join(esc) + ";")
    out.append("      ;")
    out.append("}")
    DST.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("embedded %d lines" % len(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
