#!/usr/bin/env python3
"""Embed a text file as a C string literal.

usage: embed.py <input> <varname> <output.c>
"""
import sys


def c_escape(data: str) -> str:
    out = []
    for line in data.split("\n"):
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append('"' + esc + '\\n"')
    return "\n".join(out)


def main() -> None:
    inp, var, outp = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(inp, encoding="utf-8").read()
    with open(outp, "w", encoding="utf-8") as f:
        f.write("// generated by tools/embed.py from %s — do not edit\n" % inp)
        f.write("#include <stddef.h>\n")
        f.write("const char %s[] =\n%s;\n" % (var, c_escape(data.rstrip("\n"))))


if __name__ == "__main__":
    main()
