#!/usr/bin/env python3
r"""Embed boot/prelude/*.rho into self/rho.rho as string constants.

The self-hosted compiler must not depend on a boot/ tree (or any particular
CWD) at runtime: a released image is standalone. Boot embeds the prelude via
tools/embed.py into prelude_data.c; this script is the mirror's twin — it
regenerates the prelude_*_src() functions inside self/rho.rho.

Run from the repo root after editing any boot/prelude/*.rho:

    python3 tools/embed-prelude.py

The generated strings are byte-identical to the files on disk (the lexer's
escape set covers \n \t \r \\ \" \0 \xNN).
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIRROR = ROOT / "self" / "rho.rho"

BEGIN = "// ---- embedded prelude (generated by tools/embed-prelude.py) ------"
END = "// ---- end embedded prelude -----------------------------------------"

OLD_READ_PRELUDE = """fn read_prelude(tail: string) -> Result[string, string] {
  // the prelude is the pure core plus a per-target tail (0.3.0): read both
  // and concatenate, exactly as tools/embed.py does for the boot compiler
  let cr: Result[string, string] = read_file("boot/prelude/core.rho");
  if cr.is_err() {
    return cr;
  }
  let tr: Result[string, string] = read_file(cat3("boot/prelude/", tail, ""));
  if tr.is_err() {
    return tr;
  }
  return Result.Ok(cat(cr.get_ok(), tr.get_ok()));
}"""


def escape(src: str) -> str:
    out = []
    for ch in src:
        b = ch.encode("utf-8")
        if len(b) == 1:
            c = b[0]
            if c == 0x0A:
                out.append("\\n")
            elif c == 0x09:
                out.append("\\t")
            elif c == 0x0D:
                out.append("\\r")
            elif c == 0x5C:
                out.append("\\\\")
            elif c == 0x22:
                out.append('\\"')
            elif 0x20 <= c < 0x7F:
                out.append(chr(c))
            else:
                out.append("\\x%02x" % c)
        else:
            # non-ASCII bytes pass through as UTF-8 (the sources are ASCII,
            # but keep the generator total)
            out.append(ch)
    return "".join(out)


def main() -> None:
    files = {}
    for name in ("core", "mac", "wasi", "hosted"):
        p = ROOT / "boot" / "prelude" / (name + ".rho")
        files[name] = p.read_bytes().decode("utf-8")

    fns = [BEGIN]
    for name in ("core", "mac", "wasi", "hosted"):
        fn = "fn prelude_%s_src() -> string { return \"%s\"; }" % (
            name,
            escape(files[name]),
        )
        fns.append(fn)
    fns.append(
        "// core + per-target tail, concatenated exactly as tools/embed.py\n"
        "// does for the boot compiler — the image is standalone (no boot/\n"
        "// tree, no CWD dependence)\n"
        "fn read_prelude(tail: string) -> Result[string, string] {\n"
        "  if streq(tail, \"mac.rho\") {\n"
        "    return Result.Ok(cat(prelude_core_src(), prelude_mac_src()));\n"
        "  }\n"
        "  if streq(tail, \"wasi.rho\") {\n"
        "    return Result.Ok(cat(prelude_core_src(), prelude_wasi_src()));\n"
        "  }\n"
        "  if streq(tail, \"hosted.rho\") {\n"
        "    return Result.Ok(cat(prelude_core_src(), prelude_hosted_src()));\n"
        "  }\n"
        "  return Result.Ok(prelude_core_src());\n"
        "}"
    )
    fns.append(END)
    block = "\n".join(fns)

    text = MIRROR.read_text()
    if BEGIN in text:
        pre = text.index(BEGIN)
        post = text.index(END) + len(END)
        text = text[:pre] + block + text[post:]
    elif OLD_READ_PRELUDE in text:
        text = text.replace(OLD_READ_PRELUDE, block, 1)
    else:
        sys.exit("embed-prelude: no insertion point (marker and original read_prelude both missing)")

    # sanity: the four files must round-trip through the lexer's escapes
    def unescape(lit: str) -> str:
        out = []
        i = 0
        while i < len(lit):
            c = lit[i]
            if c == "\\" and i + 1 < len(lit):
                e = lit[i + 1]
                i += 2
                if e == "n":
                    out.append("\n")
                elif e == "t":
                    out.append("\t")
                elif e == "r":
                    out.append("\r")
                elif e == "\\":
                    out.append("\\")
                elif e == '"':
                    out.append('"')
                elif e == "0":
                    out.append("\0")
                elif e == "x":
                    out.append(chr(int(lit[i : i + 2], 16)))
                    i += 2
                else:
                    out.append(e)
            else:
                out.append(c)
                i += 1
        return "".join(out)

    for name, src in files.items():
        assert unescape(escape(src)) == src, name

    MIRROR.write_text(text)
    total = sum(len(v) for v in files.values())
    print("embedded %d prelude bytes (%s)" % (total, ", ".join(files)))


if __name__ == "__main__":
    main()
