#!/usr/bin/env python3
"""Embed text files as one C string literal (inputs concatenated in order).

usage: embed.py <varname> <output.c> <input> [<input>...]

The prelude is core.rho + a per-target tail; each embedded symbol is the
concatenation, so the pure core exists exactly once.
"""
import sys


def c_escape(data: str) -> str:
    out = []
    for line in data.split("\n"):
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append('"' + esc + '\\n"')
    return "\n".join(out)


def main() -> None:
    var, outp = sys.argv[1], sys.argv[2]
    inputs = sys.argv[3:]
    data = "\n".join(open(inp, encoding="utf-8").read().rstrip("\n") for inp in inputs)
    with open(outp, "w", encoding="utf-8") as f:
        f.write("// generated by tools/embed.py from %s — do not edit\n" % " + ".join(inputs))
        f.write("#include <stddef.h>\n")
        f.write("const char %s[] =\n%s;\n" % (var, c_escape(data)))


if __name__ == "__main__":
    main()
