// The example page: import rho functions like any TypeScript module.
// The types come from index.d.rho.ts, generated by the plugin (or by
// `rho-dts src`) — tsc checks these calls for real.
import { add, exclaim, fib, half, is_even } from './index.rho';

const rows: Array<[string, string | number | boolean]> = [
  ['fib(10)', fib(10)],
  ['fib(20)', fib(20)],
  ['add(2, 40)', add(2, 40)],
  ['exclaim("hello")', exclaim('hello')],
  ['is_even(4)', is_even(4)],
  ['is_even(7)', is_even(7)],
  ['half(43)', half(43)],
];

const tbody = document.querySelector('#results tbody')!;
for (const [expr, result] of rows) {
  const tr = document.createElement('tr');
  const tdExpr = document.createElement('td');
  const tdResult = document.createElement('td');
  tdExpr.className = 'expr';
  tdResult.className = 'result';
  tdExpr.textContent = expr;
  tdResult.textContent = String(result);
  tr.append(tdExpr, tdResult);
  tbody.append(tr);
}
